In [1]:
!pip install numpy

You should consider upgrading via the 'c:\users\asiae_06\appdata\local\programs\python\python38-32\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [5]:
arr

array([1, 2, 3, 4])

In [8]:
np.zeros((3,3))
#값을 '실수로' 지정된다.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [12]:
np.empty((4,4)) #값을 초기화하지 않은 배열을 만들수 있다

array([[4.67296746e-307, 1.69121096e-306, 2.78148323e-307,
        8.90110180e-308],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 7.56605918e-307,
        1.06099790e-312]])

In [17]:
#np.arrange([0,1,2,3,4,5,6,7,8,9])
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

#  Matrix

In [18]:
arr=np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [20]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr.ndim

2

In [22]:
arr.dtype

dtype('int32')

# ndarray 배열의 type 변환

In [23]:
arr_int = np.array([1,2,3,4])
arr_int.dtype

dtype('int32')

In [25]:
arr_float=arr_int.astype(np.float64)
arr_float
arr_float.dtype

dtype('float64')

In [26]:
arr_float=arr_int.astype("float64")
arr_float
arr_float.dtype

dtype('float64')

In [29]:
arr_int = arr_float.astype(np.int64)
arr_int


array([1, 2, 3, 4], dtype=int64)

# 배열의 연산

In [33]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [40]:
arr1

array([[1, 2],
       [3, 4]])

In [41]:
arr2

array([[5, 6],
       [7, 8]])

In [38]:
arr1+arr2
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [37]:
arr1*arr2
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

# dot함수를 써서 행렬의 곱 계산

In [43]:
arr1.dot(arr2)
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [54]:
#ndarray 배열 인덱싱
arr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
arr_1 = arr[:2,1:3]
arr_1

array([[2, 3],
       [5, 6]])

In [56]:
arr_1 = arr[:2,0:2]
arr_1

array([[1, 2],
       [4, 5]])

In [63]:
arr_1 = arr[1:2,1:3]
arr_1

array([[5, 6]])

In [58]:
arr_1 = arr[:,1:3]
arr_1

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [64]:
arr.shape

(4, 3)

In [65]:
arr[1,2]

6

In [66]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [67]:
arr[[0,1,2,3],[2,0,1,2]]

array([ 3,  4,  8, 12])

In [68]:
idx = arr > 3
idx

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [71]:
arr[idx] #참인 값만 출력함

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

<ipython-input-70-7d67bf862f0c>:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  arr[[idx]]


array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])